name: neo.io and neo.rawio tests

on:
  pull_request:
    branches: [master, fix/neuralynx_mem_CI]
    types: [synchronize, opened, reopened, ready_for_review]

  # run checks on any change of master, including merge of PRs
  push:
    branches: [master, fix/neuralynx_time_CI]

jobs:
  build-and-test:
    name: Test on (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # "macos-latest",
        os: ["ubuntu-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt
          pip install -r requirements_testing.txt
          pip install -e .
      - name: Test with pytest
        run: |
          pytest neo/test/rawiotest/test_neuralynxrawio.py::TestWindowsMapping
          # only neo.rawio and neo.io
          # pytest --cov=neo neo/test/rawiotest
          # pytest --cov=neo neo/test/iotest
