name: NeoIoTest

on:
  pull_request:
    branches: [gh-test]
    types: [synchronize, opened, reopened, ready_for_review]

  # run checks on any change of master, including merge of PRs
  push:
    branches: [gh-test]


jobs:
  build-and-test:
    name: Test on (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        # "macos-latest", "windows-latest"
        os: ["ubuntu-latest", ]
        python-version: ['3.8', ]
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current year-month
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m')"

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: neo-test-env
          channels: conda-forge
          python-version: ${{ matrix.python-version }}
          clean-patched-environment-file: false

      - name: Conda location
        run: |
          conda info
          echo $CONDA_PREFIX
        # echo ${{ env.CONDA }}

      - uses: actions/cache@v3
        # the cache for python package is reset:
        #   * every month
        #   * when requirements/requirements_testing change
        id: cache-conda-env
        with:
          path: ${{ env.CONDA_PREFIX }}
          key: ${{ runner.os }}-conda-env--${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements_testing.txt') }}-${{ hashFiles('**/environment_testing.txt') }}-${{ steps.date.outputs.date }}

      - name: Install testing dependencies
        if: steps['cache-conda-env'].cache.outputs.cache-hit != 'true'
        run: |
          conda env update neo-test-env --file environment_testing.yml

      - name: Install neo
        run: |
          pip install --upgrade -e .

      - name: Get ephy_testing_data current head hash
        # the key depend on the last comit repo https://gin.g-node.org/NeuralEnsemble/ephy_testing_data.git
        id: vars
        run: |
          echo "::set-output name=HASH_EPHY_DATASET::$(git ls-remote https://gin.g-node.org/NeuralEnsemble/ephy_testing_data.git HEAD | cut -f1)"

      - uses: actions/cache@v3
        id: cache-datasets
        with:
          path: ~/ephy_testing_data
          key: ${{ runner.os }}-datasets-${{ steps.vars.outputs.HASH_EPHY_DATASET }}
          restore-keys: |
            ${{ runner.os }}-datasets

      - name: Test with pytest
        run: |
          # only neo.rawio and neo.io
          pytest neo/test/utils/test_datasets.py
          # pytest --cov=neo neo/test/rawiotest
          # pytest --cov=neo neo/test/iotest
